const categories = [
  {
    category: 'The Pentateuch',
    books: ['Genesis', 'Exodus', 'Leviticus', 'Numbers', 'Deuterenomy'],
  },
  {
    category: 'Historical Books',
    books: [
      'Joshua',
      'Judges',
      'Ruth',
      '1 Samuel',
      '2 Samuel',
      '1 Kings',
      '2 Kings',
      '1 Chronicles',
      '2 Chronicles',
      'Ezra',
      'Nehemiah',
      'Esther',
    ],
  },
  {
    category: 'Poetry Books',
    books: ['Job', 'Psalms', 'Proverbs', 'Ecclesiastes', 'Songs of Solomon'],
  },
  {
    category: 'Major Prophets',
    books: ['Isaiah', 'Jeremiah', 'Lamentations', 'Ezekiel', 'Daniel'],
  },
  {
    category: 'Minor Prophets',
    books: [
      'Hosea',
      'Joel',
      'Amos',
      'Obadiah',
      'Jonah',
      'Micah',
      'Nahum',
      'Habakkuk',
      'Zephaniah',
      'Haggai',
      'Zechariah',
      'Malachi',
    ],
  },
  {
    category: 'Gospels',
    books: ['Matthew', 'Mark', 'Luke', 'John'],
  },
  {
    category: 'History of the Church',
    books: ['Acts of the Apostles'],
  },
  {
    category: 'Pauline Epistles',
    books: [
      'Romans',
      '1 Corinthians',
      '2 Corinthians',
      'Galatians',
      'Ephesians',
      'Philippians',
      'Colossians',
      '1 Thessalonians',
      '2 Thessalonians',
      '1 Timothy',
      '2 Timothy',
      'Titus',
      'Philemon',
    ],
  },
  {
    category: 'General Epistles',
    books: [
      'Hebrews',
      'James',
      '1 Peter',
      '2 Peter',
      '1 John',
      '2 John',
      '3 John',
      'Jude',
      'Revelations',
    ],
  },
];

module.exports = categories;
