export const SET_ALL_BOOKS_REQUEST = 'SET_ALL_BOOKS_REQUEST';
export const SET_ALL_BOOKS_SUCCESS = 'SET_ALL_BOOKS_SUCCESS';
export const SET_ALL_BOOKS_FAIL = 'SET_ALL_BOOKS_FAIL';

export const SET_BOOK_REQUEST = 'SET_BOOK_REQUEST';
export const SET_BOOK_SUCCESS = 'SET_BOOK_SUCCESS';
export const SET_BOOK_FAIL = 'SET_BOOK_FAIL';

export const SET_CHAPTER_REQUEST = 'SET_CHAPTER_REQUEST';
export const SET_CHAPTER_SUCCESS = 'SET_CHAPTER_SUCCESS';
export const SET_CHAPTER_FAIL = 'SET_CHAPTER_FAIL';

export const SET_VERSE_REQUEST = 'SET_VERSE_REQUEST';
export const SET_VERSE_SUCCESS = 'SET_VERSE_SUCCESS';
export const SET_VERSE_FAIL = 'SET_VERSE_FAIL';

export const SET_TEXT_REQUEST = 'SET_TEXT_REQUEST';
export const SET_TEXT_SUCCESS = 'SET_TEXT_SUCCESS';
export const SET_TEXT_FAIL = 'SET_TEXT_FAIL';
